### ISSUE TITLE
Decide on a versioning system

### ISSUE THREAD

**Issue by rth** [icubam/icubam#121]
As mentioned in https://github.com/icubam/icubam/pull/113#discussion_r401215066 by @dulacarnold 
> I think we're not set up with a good versioning system. We started putting versions in the config.toml but that was a bad idea, I think bumping the setup.py version every time we deploy could work (a).

Opening an issue to centralize the discussion around it, as there have been lots of comments in different places.

Earlier, @rprimet suggested to use https://github.com/warner/python-versioneer for it (b). Another alternative could be https://github.com/pypa/setuptools_scm (comparison with versioneer in https://github.com/icubam/icubam/pull/82) (c).

Also in https://github.com/icubam/icubam/pull/82 @Deathn0t proposed another solution to load version from `setup.cfg` (d).

So there are 4 possible approaches so far a-b-c-d.

**Comment by rth** [comment]
Personally I think a) is fine as long as deployments are not too frequent. I'll investigate b and c to see if they could work in this use-case.

**Comment by rth** [comment]
Version is currently set in 3 place,
 - setup.py (or setup.cfg)
 - `icubam/__init__.py` (after https://github.com/icubam/icubam/pull/113 is merged)
 - `resources/config.toml`

and ideally we would need to reduce this to 1 even for approach a).

**Comment by Deathn0t** [comment]
Personally to manage projects simply I usually set manually the version in a `icubam/__version__.py` which is loaded in the `icubam/__init__.py`. And the `setup.py` import this `__version__` attribute from the icubam package. Till now I never used the `setup.cfg` just thought it was a more standard way so created one in the #82. I also usually put all requirements in a list inside the `setup.py` so that everything is in the same place. Then I create the release tag using [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/), which is very easy and well organized for features, hot-fix, develop and release branches.  To upload and build the wheel I use [twine](https://pypi.org/project/twine/) which enables you to upload to PyPI in a secure/easy manner. Here is a sample `setup.py` I made for a project ([example setup.py](https://github.com/deephyper/deephyper/blob/master/setup.py)), it references required packages, command lines, version, twine for PyPI and other info. It works well for extras packages used in test or documentation.

**Comment by rth** [comment]
I agree @Deathn0t . The choice of `setup.py` vs `setup.cfg` is orthogonal to this issue.  `setup.cfg` is indeed a bit nicer, but in the end I would say it doesn't really matter much.

The goal of this is to reduce the number of places where the version needs to be manually updated (currently 3) and if possible automate some of it with respect to the git tag.

**Comment by rth** [comment]
One possible solution proposed in https://github.com/icubam/icubam/pull/127
