### ISSUE TITLE
Reduce the size of the Docker image

### ISSUE THREAD

**Issue by marccarre** [icubam/icubam#237]
## Problem

The current docker image is rather large & heavy, which may:

- make it more costly (time, bandwidth, hosting requirements, etc.) to run `icubam`,
- make it less convenient for users to upgrade,
- make it slower to run CI,
- etc.

```console
$ docker images
REPOSITORY  TAG     IMAGE ID      SIZE
icubam      latest  50b08979695e  1.68GB
```

We should probably be able to reduce the image size by one order of magnitude given the size of these potential base images:

```console
$ docker images
REPOSITORY                          TAG       IMAGE ID      SIZE
python                              3.7-slim  74ac77e9873a  179MB
python                              3-slim    56930ef6f6a2  193MB
gcr.io/distroless/python3-debian10  latest    abd94187f786  52.2MB
gcr.io/distroless/python3           latest    be51572a0d67  49.6MB
```

## Suggestion

1. Reduce 3rd party dependencies as much as possible? (See also #235.)
2. ~Separate dev and prod Python dependencies?~ (Already `requirements.txt` and `requirements-dev.txt`.)
3. Separate build-time dependencies from run-time dependencies, using e.g. Docker multi-stage builds?
4. Using a lighter base image?
5. Following Docker best practices:

    1. have each `RUN` statement clean after itself, e.g.:

        ```console
        RUN apt-get update && apt-get install -y \
                ${PACKAGE} && \
            rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        ```
    2. have a `.dockerignore` file to ensure we don't accidentally package more than required,

**Comment by rprimet** [comment]
Yes, sounds nice!

(I believe the rationale for using the ubuntu base image is that previously, deployment would happen on a Ubuntu VM)

One added benefit is that, all dependencies being fetched on PyPI, we could do away with all the conda-related stuff in the Dockerfile?

Something to be mindful of, though, is that there was an implicit (except in the docs) dependency on sqlite >= 3.24.0 (which is newer than e.g. the one packaged in ubuntu 18.04 and was pulled by conda). But maybe this isn't even required now since the project moved from straight sql queries to sqlalchemy? cc @olivierteboul @dulacarnold?

As an aside maybe it'd be worth running the unit tests in the [docker packaging workflow](https://github.com/icubam/icubam/blob/master/.github/workflows/docker-package.yml) as well?

**Comment by dulacarnold** [comment]
I would keep the version if possible, I'm not sure what sqlalchemy expects... But the sqlite is part of python3.7 anyways iiuc...

**Comment by pgraverdy** [comment]
Some initial testing wrt image size

| img | size | details |  
| --- | --- | --- |
| default  | 1.69GB  |  Ubuntu 18.04 with conda, Python 3.8 | 
| 1  | 2.45GB  | Using python3.7 base image |
| 2 |  2.43GB | +apt cache clean |
| 3 |  2.33GB | +minimal package install   |
| 4 |  2.3GB |  +same Python version for image and conda |
| 5 |  1.49GB | +no conda |
| 7 |  835MB | +using python3.7-slim-buster image |

So to get a final image that is smaller (about 50%) we need the slim python image and do away with conda.

The git history for the last image gives the following numbers
- base image: 200MB
- the update and system package instal takes 87.1MB
- installing requirements takes 492MB

The build is still quite slow due to the many requirements.

**Comment by dulacarnold** [comment]
@pgraverdy after discussion in devops chan, it looks like we're already using python3.8.2 in prod, so we should probably move the docker image to that.
