### ISSUE TITLE
unit tests (test_plot) failing with python 3.7

### ISSUE THREAD

**Issue by rprimet** [icubam/icubam#258]
Using python 3.7.7 I get the following errors when running `pytest`:

`E       ValueError: unsupported pickle protocol: 5`

This is solved by moving to python 3.8 but the minimal version of python should be documented somewhere (or maybe an older pickling protocol can be used for the tests?)

**Comment by rth** [comment]
This is likely due to the predicu integration, you can ignore the failing test, it's not currently used in the running servers in any way.

We shouldn't use pickles indeed as they are not portable across python version (cc @tgy ), there is still active development happening for predicu (e.g. https://github.com/icubam/icubam/pull/240) and we'll try to address this.

BTW, if we want to support Python 3.7 we should add it to CI.

**Comment by rth** [comment]
Interestingly the issue happens when loading HDF5 file,
```
    @pytest.mark.parametrize("name", PLOTS)
    def test_generate_plots(name, tmpdir, monkeypatch):
      output_dir = str(tmpdir.mkdir("sub"))
      test_public_data_path = os.path.join(BASE_PATH, "tests/data/public_data.h5")
>     test_public_data = pd.read_hdf(test_public_data_path, 'values')
[...]
    def fromarray(self, array):
        # We have to check for an empty array because of a possible
        # bug in HDF5 which makes it claim that a dataset has one
        # record when in fact it is empty.
        if array.size == 0:
            return None
>       return pickle.loads(array.tostring())
E       ValueError: unsupported pickle protocol: 5
```
so this will be resolved once https://github.com/icubam/icubam/pull/240 is merged, as it removes the use of these files.

**Comment by tgy** [comment]
@rth HDF uses pickle to store some objects (here `datetime` objects I think) because it does not have native support for them... anyhow, like you said this is not an issue anymore.

**Comment by rth** [comment]
Should be resolved in https://github.com/icubam/icubam/pull/240
